### ISSUE TITLE
Trouble compiling

### ISSUE THREAD

**Issue by xantari** [vpdb/agent#29]
Hi Freezy,

I'm checking this out as I wanted to look into the Vpdb implementation and some of the other work you did on this but can't get it to compile on a fresh checkout.

I'm in dependency hell.

You have Splat 2.0 in package.config, but reactiveui 7.4.0 must use one below that.

So I downgraded splat, but then get this: 

Severity	Code	Description	Project	File	Line	Suppression State
Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\SQLitePCL.raw_basic.0.8.6\build\net45\SQLitePCL.raw_basic.targets.	VpdbAgent	C:\VisualStudio\VPDB\Agent\VpdbAgent\VpdbAgent.csproj	542	

Whats interesting is the SQLitePCL.raw_basic.0.8.6 is being referenced as a build target in the .csproj, but the nuget packages.config points to 0.9.0-pre8 of that assembly.

So I'm guessing something got hosed up with the .csproj

**Comment by xantari** [comment]
There also appears to be some missing files.

I believe it is in the VpdbAgent.Data.Objects namespace.

There is supposed to be an IMenuManager somewhere, but I can't find it.

**Comment by xantari** [comment]
FYI, I was able to fix up the .csproj file (I beleve perhaps a previous nuget update may have hosed the file up). It probably works in your environment because you still have the package folders for the older releases of some of the nuget binaries.

**Comment by freezy** [comment]
I'll have a look at this later today!

**Comment by freezy** [comment]
Sorry I screwed that up. Should be fixed now.

VPDB is currently still going through some refactoring, so depending on which part you're looking, you'll find some changes soon.

**Comment by xantari** [comment]
Thanks!!

**Comment by xantari** [comment]
@freezy I am still not seeing IMenumanager or anything in the VpdbAgent.Data.Objects which is referenced in the vpdbAgent.Tests solution?

**Comment by xantari** [comment]
It looks like PlatformDatabase and IPlatformManager is also missing in the tests library

**Comment by freezy** [comment]
Just unload the test project, it's unmaintained until I finish the refactoring.
